### ISSUE TITLE
链式调用的时候返回结果不对

### ISSUE THREAD

**Issue by surj07** [HXWfromDJTU/blog#1]
new MyPromise ((resolve, reject) => {
    setTimeout(() => {
        console.log(111);
        resolve(222);
    }, 5000);
}).then((data) => {
    return new MyPromise ((resolve, reject) => {
        setTimeout(() => {
            console.log(data);
            resolve(333);
        }, 3000);
    });
}).then((data) => {
    console.log(data);
});

这种情况下，打印出来的是 
111  222   222
正确的结果应该是
111  222   333

_resolve方法有问题

**Comment by HXWfromDJTU** [comment]
> new MyPromise ((resolve, reject) => {
> setTimeout(() => {
> console.log(111);
> resolve(222);
> }, 5000);
> }).then((data) => {
> return new MyPromise ((resolve, reject) => {
> setTimeout(() => {
> console.log(data);
> resolve(333);
> }, 3000);
> });
> }).then((data) => {
> console.log(data);
> });
> 
> 这种情况下，打印出来的是
> 111 222 222
> 正确的结果应该是
> 111 222 333
> 
> _resolve方法有问题

好的找时间测试一下
